services: 
  postgres-db-banking-service:
    image: postgres:14
    container_name: postgres-db-banking-service-container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admins
      - POSTGRES_DB=db_agencia
    ports:
      - 5433:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql